### ISSUE TITLE
Beautify Pydantic errors

### ISSUE THREAD

**Issue by sregales-TNO** [equinor/everest#31]
**Issue**
Users are unable to understand Pydantic errors
Example:
![image](https://github.com/equinor/everest/assets/82570369/5e9be8e9-9eef-45ab-9691-047abf6193c7)
Pydantic error message
![image](https://github.com/equinor/everest/assets/82570369/59614352-3def-46e6-a4b2-fc63f4a46ba5)
It's not clear to the user that the problem is that `variables` is not indented properly, thus not recognised by Pydantic as a subfield of `controls`.

**Definition of done**
A clear, concise understandable error for non-developers.

**Comment by DanSava** [comment]
Changed the code to make them more readable to something like 
```
Found  17 validation errors:

controls -> name
    * Required field 'name' is missing
    * Required field 'name' is missing
controls -> type
    * Required field 'type' is missing
    * Required field 'type' is missing
controls -> variables
    * Required field 'variables' is missing
    * Required field 'variables' is missing
    * Required field 'variables' is missing
controls -> xxxx
    * Unknown field 'xxxx' not permitted
controls -> initial_guess
    * Input should be a valid number, unable to parse string as a number
controls -> mxax
    * Unknown field 'mxax' not permitted
controls -> test
    * Unknown field 'test' not permitted
objective_functions
    * Required field 'objective_functions' is missing
model -> realizations
    * Input should be a valid integer, unable to parse string as an integer
input_constraints -> weights -> point_0.x-0
    * Input should be a valid number, unable to parse string as a number
install_templates
    * Input should be a valid dictionary or instance of InstallTemplateConfig
    * Input should be a valid dictionary or instance of InstallTemplateConfig
variables
    * Unknown field 'variables' not permitted
```

I then realized that the messages are just arbitrarily more readable and I cannot argue if these error messages are more easy to understand by non-developers. Still, I could not find an exhaustive way to distinguish indentation errors and avoid a the confusing error message. So I am closing this issue and deciding on dealing with user questions regarding them as part of user support.
