### ISSUE TITLE
Initialize ert only through LibresFacade

### ISSUE THREAD

**Issue by yngve-sk** [equinor/everest#33]
Within ert, ErtConfig will require internal plugins to be used. Therefore it makes sense to let ert internally decide how it should give a config. 

So to solve this issue:
Remove all `ErtConfig.from_dict` / `ErtConfig.from_file` calls and go through LibresFacade, this may involve creating an endpoint in `LibresFacade` that initializes an ert config with plugins from the plugin manager.

**Comment by oyvindeide** [comment]
Not sure I agree we should extend LibresFacade, as we have worked to reduce the impact of that class, as it is another state holding wrapper. Are there other solutions here?

**Comment by yngve-sk** [comment]
Closing for now, probably a better solution on the ert side.
