### ISSUE TITLE
Using everest branch reorders keys, causing large diff in files

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everest#77]
**Issue**
As a user I would like to preserve the config file structure when using `everest branch` so that we keep a relatable structure.
The main goal is to have two config files with a minimal diff, where the diff is not caused by reordering existing keys.

**Definition of done**
When `everest branch <config_file> <new_config_file> -b #` can produce a `new_config_file` in the same order as of the original `config_file`.

**Comment by oyvindeide** [comment]
@roliveira is the `branch` functionality useful? There does not seem there is much usage of it.

**Comment by roliveira** [comment]
I can't say for sure if it's useful, only that it haven't been used recently. I think that it is safe to mark it as deprecated.
